name: 02 - Workflow Events

on:
  push:
    branches:
        - 'main'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"


jobs:
  know-event-name:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
